name: identity
description: Universal Identity library
version: 0.1.0
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-identity

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sso: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
